mutation leaveGroup(
    $id: Int!
    $characterId: Int!
) {
    leaveGroup(leaveGroupInput: {
        id: $id
        characterId: $characterId
    }){
        id
        name
        dueDate
    }
}